name: Continuous Integration

on:
  push:
    branches: [ master ]
    paths-ignore: ['.github/**']
  pull_request:
    paths-ignore: ['.github/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Run Build
        run: npm run build
